import { notFound } from "next/navigation";
import { getSalesInvoice } from "@/app/actions/finance";
import { formatMoney } from "@/lib/utils";
import { brand } from "@rkyves/shared";
import { PrintButton } from "@/components/print-button";

export default async function InvoicePrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const data = await getSalesInvoice(id);
  if (!data) notFound();
  const { invoice, lines, customer, company } = data;
  const outstanding = Number(invoice.totalAmount) - Number(invoice.paidAmount || 0);

  return (
    <div className="min-h-screen bg-[var(--color-bg)]">
      <div className="mx-auto max-w-3xl bg-white p-8 text-[var(--color-ink,#111)] print:p-0">
        <style>{`@media print { .no-print { display: none !important; } }`}</style>
        <div className="no-print mb-6 flex justify-end">
          <PrintButton />
        </div>
        <header className="mb-8 flex items-start justify-between border-b border-[var(--color-border)] pb-4">
          <div>
            <p className="text-2xl font-semibold text-[var(--color-primary)]">{company.name}</p>
            <p className="text-sm text-[var(--color-muted)]">{company.legalName || brand.name}</p>
            {company.gstin ? <p className="text-sm">GSTIN: {company.gstin}</p> : null}
            <p className="text-sm">{[company.city, company.state].filter(Boolean).join(", ")}</p>
          </div>
          <div className="text-right">
            <p className="text-lg font-semibold">TAX INVOICE</p>
            <p className="text-sm">{invoice.number}</p>
            <p className="text-sm">Date: {invoice.invoiceDate}</p>
          </div>
        </header>
        <section className="mb-6 grid gap-4 text-sm sm:grid-cols-2">
          <div>
            <p className="font-medium uppercase tracking-wide text-[var(--color-muted)]">Bill to</p>
            <p className="font-semibold">{customer?.name || "—"}</p>
            {customer?.gstin ? <p>GSTIN: {customer.gstin}</p> : null}
            {customer?.billingAddress ? <p>{customer.billingAddress}</p> : null}
          </div>
          <div className="sm:text-right">
            <p>Status: {invoice.status}</p>
            <p>Paid: {formatMoney(invoice.paidAmount)}</p>
            <p>Outstanding: {formatMoney(outstanding)}</p>
          </div>
        </section>
        <table className="mb-6 w-full border-collapse text-sm">
          <thead>
            <tr className="border-b border-[var(--color-border)] text-left">
              <th className="py-2">#</th>
              <th className="py-2">Description</th>
              <th className="py-2">Qty</th>
              <th className="py-2">Rate</th>
              <th className="py-2">GST%</th>
              <th className="py-2 text-right">Amount</th>
            </tr>
          </thead>
          <tbody>
            {lines.map((l, idx) => (
              <tr key={l.id} className="border-b border-[var(--color-border)]/60">
                <td className="py-2">{idx + 1}</td>
                <td className="py-2">{l.description}</td>
                <td className="py-2">
                  {l.quantity} {l.uom}
                </td>
                <td className="py-2">{formatMoney(l.unitPrice)}</td>
                <td className="py-2">{l.gstRate}</td>
                <td className="py-2 text-right">{formatMoney(l.lineTotal)}</td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="ml-auto max-w-xs space-y-1 text-sm">
          <div className="flex justify-between">
            <span>Subtotal</span>
            <span>{formatMoney(invoice.subtotal)}</span>
          </div>
          <div className="flex justify-between">
            <span>Tax</span>
            <span>{formatMoney(invoice.taxAmount)}</span>
          </div>
          <div className="flex justify-between border-t border-[var(--color-border)] pt-2 text-base font-semibold">
            <span>Total</span>
            <span>{formatMoney(invoice.totalAmount)}</span>
          </div>
        </div>
        <p className="mt-10 text-xs text-[var(--color-muted)]">
          Generated by {brand.name}. Use Print → Save as PDF for a PDF copy.
        </p>
      </div>
    </div>
  );
}
